import Head from "next/head"
import Link from "next/link"
import { Icon } from "@chakra-ui/react"
import { BsBoxArrowInRight } from "react-icons/bs"
import styles from "../styles/Home.module.css"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Admin Dashboard Cuenta-Nombre</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<div>
					<div>
						<h1 className={styles.title}>
							LogIn Dashboard Cuenta-Nombre
						</h1>
					</div>
				</div>
			</main>
			<div className={styles.main}>
				<Link href='/dashboard'>
          <div className={styles.button}>
            <p className={styles.texto}>
              Dashboard
            </p>
            <Icon
              as={BsBoxArrowInRight}
              fontSize='2xl'
              className='active-icon'
            />
          </div>
				</Link>
			</div>

			<footer className={styles.footer}></footer>
		</div>
	)
}
